### ISSUE TITLE
compile error: make: *** No rule to make target '../src/redismodule.h', needed by 'slock.xo'.  Stop.

### ISSUE THREAD

**Issue by base64coder** [wujunwei/redlock#3]
If I execute `make`, the error will output: `make: *** No rule to make target '../src/redismodule.h', needed by 'slock.xo'.  Stop.`
so, i need do something like this:

```shell
git clone --recursive --depth=1 git@github.com:redis/redis.git
ln -s redis/src .
git clone --recursive git@github.com:wujunwei/redlock.git
cd redlock

make
```

**Comment by wujunwei** [comment]
Put this project `redlock` under the same fold level as `src` .

I will explain in detail later in the **README**.

**Comment by wujunwei** [comment]
If you don't have more question,I will close it after 30 days.
